lmcrean/dottie

- backend/tests/api-comprehensive.test.js
- Updated test structure to utilize Vitest for testing framework.
- Replaced Playwright test commands with Supertest for API requests.
- Implemented server lifecycle management with beforeAll and afterAll hooks.
- Adjusted response handling to align with Supertest's API.
- Enhanced test cases for better clarity and consistency.
> Refactor API comprehensive tests to use Vitest and Supertest

- backend/db/index.js
DM for env file.
You could test the connection by running the following command
cd backend && node --experimental-vm-modules -e "import('./db/index.js').then(async ({default: db}) => { try { const tables = await db.raw('SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = \'BASE TABLE\''); console.log('Available tables:', tables); } catch(err) { console.error('Error:', err); } finally { setTimeout(() => process.exit(), 1000); } });"
> feat: Add Azure SQL connection config

- backend/.gitignore
- backend/package.json
http://dottie-api.azurewebsites.net/api/hello
http://dottie-api.azurewebsites.net/api/sql-hello
Deployed 2 things with the below changes. Having difficulties deploying the Dottie frontend
> Deploy backend API to Azure with working /api/hello endpoint

- dottie-app/src/App.tsx
- dottie-app/src/pages/auth/SignIn.tsx
- dottie-app/src/pages/auth/SignUp.tsx
Built UI for sigin and siginup
> Auth Pages 

- dottie-app/context/AssessmentResultContext.tsx
- dottie-app/hooks/use-assessment-result.ts
- dottie-app/src/main.tsx
- Add AssessmentResultContext with type-safe state management
- Create a useAssessmentResult hook with pattern determination and recommendations
- Integrate AssessmentResultProvider in main.tsx
- Add session storage persistence for assessment data
- Define assessment result types and interfaces
> feat: add AssessmentResult context and provider setup

- dottie-app/components/ui/input.tsx
- dottie-app/context/AuthContext.tsx
- dottie-app/src/api/auth.ts
- dottie-app/src/main.tsx
- dottie-app/src/pages/auth/SignIn.tsx
- dottie-app/src/pages/auth/SignUp.tsx
- dottie-app/src/routes/ProtectedRoute.tsx
**Description:**
This pull request introduces authentication functionality, including user registration and login, along with API integration for authentication.
**Changes Implemented:**
Created an authentication context to manage user sessions.
**Implemented API calls for:**
**Signup (/api/auth/signup)**
**Login (/api/auth/login)**
> feat: Implemented Auth and API call for Authentication

- frontend/src/api/user/__tests__/unit/user.test.ts
- Removed mock implementation for resetPassword to test actual function.
- Added tests for password reset request and completion, including error handling.
- Updated password update tests to include response validation and error handling for incorrect current password.
> test: enhance user API tests for password reset and update functionality

- frontend/src/pages/assessment/period-duration/page.tsx
Period duration page will now have consistent width as others
> Period Duration Consistent Width

- frontend/src/pages/auth/sign-up.tsx
Resolved the issue #142  with handling different states for password visibility.
> Issue #142 : Frontend (auth): Password visibility toggle affects both fields simultaneously

- backend/routes/assessment/delete/controller.js
- backend/routes/assessment/getDetail/controller.js
- backend/routes/assessment/getDetail/routes.js
- backend/routes/assessment/update/controller.js
- update and Delete endpoints not working in test-page. - Now fixed. 
- Updated `req.params.id` to `req.params.assessmentId` across assessment-related controller files for better readability and consistency.
- Adjusted route path in `getDetail/routes.js` from `/:id` to `/:assessmentId` to reflect this change.
- Minor improvements for clarity and parameter naming alignment across the delete, detail, and update endpoints.
> Refactor `req.params.id` to `req.params.assessmentId` for Clarity and Consistency

- frontend/package-lock.json
- frontend/package.json
- frontend/src/pages/landing-page/page.tsx
I implemented a fade-in effect for the homepage to enhance the visual appeal. This animation provides a smoother transition for users as they enter the site.
Additionally, I updated the footer to display the current date dynamically, ensuring that the website always shows the correct date. 
https://github.com/user-attachments/assets/1a4542a1-1d34-4b01-9985-49b469880df3
> feat(ui): animate homepage

- frontend/src/api/auth/requests/postLogout/Request.ts
> Include refresh token in logout API request body to fix missing token

- frontend/src/pages/user/PasswordUpdateForm.tsx
> feat(UI): Add password visibility toggles to Password Update Form

- frontend/src/components/AuthLayout.tsx
- frontend/src/pages/assessment/age-verification/page.tsx
- frontend/src/pages/assessment/resources/page.tsx
- frontend/src/pages/assessment/results/page.tsx
> Frontend (assessment): Hide download and Share buttons with display:none

- frontend/src/pages/auth/sign-in.tsx
> Frontend (auth): hide forgot your password? functionality in auth view

- frontend/src/api/auth/requests/postLogout/Request.ts
- frontend/src/context/AuthContext.tsx
- frontend/src/pages/user/PasswordUpdateForm.tsx
Issue #91 Integration of password update is resolved.
You can check the code changes and it's also redirecting back to sign in after password change.
> Issue #91 Resolved.

- frontend/src/pages/user/account-form.tsx
**Before:** Multiple stacked modals on rapid clicks
**After:** Only one modal appears regardless of click speed
Fixes: #233
> [Bug] Multiple "Delete Account" Modals Open on Repeated Clicks

- frontend/src/App.tsx
- frontend/src/components/navigation/Header.tsx
- frontend/src/pages/landing-page/page.tsx
update the code to remove React.FC from header.tsx, landingpage.tsx and app.tsx
> Frontend: refactor old style Typescript #258

- frontend/src/globals.css
- frontend/src/pages/auth/sign-in.tsx
I am working on this. Issue #254
> Styling (landing page): "Menstrual Health" fades from black to pink after 3 seconds

- frontend/src/components/AnimatedLogo.tsx
- frontend/src/pages/auth/sign-in.tsx
- frontend/src/pages/auth/sign-up.tsx
https://github.com/user-attachments/assets/56267e1d-99ab-4b0d-aff9-08c3c48a76bf
- Issue link: #
Resolves #271
> Create Reusable Animated Logo Component

- README.md
> Docs: Add a step explaining need to create a fork for repo

- frontend/package-lock.json
- frontend/src/App.tsx
- frontend/src/routes/ProtectedRoute.tsx
> fix: fixed unauthenticated access to protected routes #263

- frontend/src/pages/chat/page.tsx
> Integration(chat): there is a duplicate chat when opening AI chat feature in UI

- frontend/src/pages/assessment/age-verification/page.tsx
- frontend/src/pages/assessment/cycle-length/page.tsx
- frontend/src/pages/assessment/flow/page.tsx
- frontend/src/pages/assessment/history/[id]/page.tsx
- frontend/src/pages/assessment/pain/page.tsx
- frontend/src/pages/assessment/period-duration/page.tsx
- frontend/src/pages/assessment/symptoms/page.tsx
- frontend/src/pages/chat/FullScreenChat.tsx
- frontend/src/pages/chat/page.tsx
Resolves #298 , #300 
https://github.com/user-attachments/assets/086bd3d6-c474-4d90-b2b1-9680392b5027
- Issue link: #
> Dark Mode Hover State Affects All Radio

- frontend/src/pages/auth/signout.tsx
- frontend/src/pages/user/account-form.tsx
Resolves #299 
- Issue link: #
> Dark Mode UI Inconsistencies 

- CONTRIBUTING.md
- CONTRIBUTING_issues_tab.md
updated F.A.Q. section and added more issue tab guidance
- clarified role of Pull Reqs tab
- clarified role of commenting on issues
- introduced informal (Draft) issues for making notes
N/A
N/A
> Update CONTRIBUTING.md with clarified Issue tab guidance

- backend/db/database.js
- backend/db/migrations/initialSchema.js
- backend/db/supabase/schema/supabase-schema.sql
- backend/routes/setup/database/hello.js
- backend/routes/setup/database/status.js
- **Summary of work:**  fixed the endpoints for database hello and status In test-page | developer mode
- **Scope of changes:**  ```backend/db/database.js```, ```backend/routes/setup/database/hello.js```, ```backend/routes/setup/database/status.js```
- **Testing instructions:** 
1.  run `npm run db:init` to add health check table to database  
2. test the database endpoints ( status and hello)  in test page | developer mode.
Dev mode =>
> Fix: Test-page database status endpoints

- pull_request_template.md
Attempting to improve developer experience with
- more DRY principles
- more consistency in formatting
- better readability
- clearer guidance on linking issues
> Streamline workflow in pull_request_template.md for cleaner developer experience

- frontend/src/pages/assessment/detail/page.tsx
- frontend/src/pages/chat/chat-detail/components/buttons/send-initial-message/SendInitialMessageButton.tsx
Please provide a clear and concise description of the changes made in this PR.Fixes button alignment and sizing inconsistencies in the assessment detail page to improve UI consistency.
Before submitting this PR, the following **must** be confirmed:
Closes #345
> Frontend(assessment detail buttons): standardize sizing and alignment

- README.md
Please attach relevant screenshots or screen recordings that demonstrate UI/UX changes, Component behavior and /or Error messages (if applicable).
> Chore: update README header screenshot

- ux-design/CONTRIBUTING.md
- ux-design/damage-report-template.md
- CONTRIBUTING.md file created with guidance, strategy and overview for design
- Figma File set up on cloud,
- This in the longterm will contribute to the enhancement of the Design, the project has reached MVP and requires a coherant wireframe to be optimised
Please attach relevant screenshots or screen recordings that demonstrate UI/UX changes, Component behavior and /or Error messages (if applicable).
> Project: implement UX Designer Workflow with Figma File

- frontend/e2e/CompleteAssessmentFlow.spec.ts
- frontend/global-teardown.ts
- frontend/package.json
- frontend/playwright.config.ts
Please provide a clear and concise description of the changes made in this PR.
E2E tests previously returned frontend only results -- test would run, handle frontend actions, then fail due to no connection to backend.
Please attach relevant screenshots or screen recordings that demonstrate UI/UX changes, Component behavior and /or Error messages (if applicable). 
https://github.com/user-attachments/assets/b3513fe0-b889-4528-a075-623944d811b8
see screenshot
Please provide step-by-step testing instructions. _If any specific test data or test accounts are needed, mention them here._
1. Pull this branch
2. Follow setup instructions correctly as per `README-developers.md`
3. Open terminal
4. `cd ../frontend; npx run test:dev:auth` will pass
5. additionally, can check visuals with `cd …
> E2E Testing: Confirm Integration of frontend and backend with `AuthRandomUser.spec.ts` pass. Previously E2E tests returned frontend only.
